# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robotone', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoritorizatorRobot',
            new_name='MonitorizatorRobot',
        ),
    ]
