# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotone', '0003_auto_20180710_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorizatorrobot',
            name='state',
            field=models.CharField(choices=[(1, 'Waiting'), (2, 'Working'), (3, 'Finished')], max_length=50),
        ),
        migrations.AlterField(
            model_name='monitorizatorrobot',
            name='type',
            field=models.CharField(choices=[(1, 'robotA'), (2, 'robotB')], max_length=50),
        ),
    ]
