# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotone', '0004_auto_20180710_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorizatorrobot',
            name='state',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Working', 'Working'), ('Finished', 'Finished')], max_length=50),
        ),
        migrations.AlterField(
            model_name='monitorizatorrobot',
            name='type',
            field=models.CharField(choices=[('robotA', 'robotA'), ('robotB', 'robotB')], max_length=50),
        ),
    ]
