# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotone', '0005_auto_20180710_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorizatorrobot',
            name='state',
        ),
        migrations.AddField(
            model_name='monitorizatorrobot',
            name='status',
            field=models.CharField(choices=[(1, 'Waiting'), (2, 'Working'), (3, 'Finished')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='monitorizatorrobot',
            name='type',
            field=models.CharField(choices=[(1, 'robotA'), (2, 'robotB')], default=1, max_length=50),
        ),
    ]
