# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotone', '0006_auto_20180710_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorizatorrobot',
            name='status',
            field=models.CharField(choices=[('Waiting', 'waiting'), ('Working', 'working'), ('Finished', 'finished')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='monitorizatorrobot',
            name='type',
            field=models.CharField(choices=[('RobotA', 'robotA'), ('RobotB', 'robotB')], default=1, max_length=50),
        ),
    ]
